= Beta1 Release Notes: SUSE CaaS Platform v4

WARNING: "This is a BETA release and NOT intended for production usage."

This document lists what is coming with SUSE CaaS Platform v4, what are the differences with v3.
Tested Platforms

* VMWare 6.0 (vmdk file)
* SUSE Openstack Cloud
* Bare metal

== Changes to the underlying operating system:

=== New MicroOS

SUSE CaaS Platform is based on MicroOS, which is a special flavor of SUSE Linux Enterprise Server.

* SUSE CaaS Platform v3 was based on SLE 12 SP3, while v4 is based on SLE 15.

=== NTP Client Configuration

NTP Clients no longer configured automatically on the nodes, user must configure themselves using either yast2 installer, cloud-init, autoyast, or manual config via salt (https://bugzilla.suse.com/show_bug.cgi?id=1118473)

*  *Solution*: User must specify NTP servers to be used in (either):
** YaST installer: specify servers in the "NTP Servers" field
** cloud-init: https://susedoc.github.io/doc-caasp/develop/caasp-deployment/single-html/#sec.deploy.cloud-init
** AutoYaST: https://susedoc.github.io/doc-caasp/develop/caasp-deployment/single-html/#sec.deploy.autoyast and https://www.suse.com/documentation/sles-15/singlehtml/book_autoyast/book_autoyast.html#Configuration.Network.Ntp

== Changes to the Kubernetes stack

* Updated Kubernetes version: v3 shipped 1.10 via the updates channel. V4 ships with Kubernetes 1.13
* Container images are distributed using the SUSE container registry instead of being wrapped into RPM packages. This is reducing the size of our installation medias and the amount of disk space required on the nodes of the cluster. Although this doesn't immediately affect the update process, it will also facilitate updates in the future by making reboots obsolete when a container image changes.
* Tech preview: Cilium SDN. Cilium is allowing CaaS Platform users to take advantage of Kubernetes Network Policies. Flannel is still fully supported as part of v4.
** https://susedoc.github.io/doc-caasp/beta1/v4/caasp-deployment/single-html/#deployment.appendix.cilium
** Advantages of Cilium over flannel:
+
** Supports Kubernetes Network policy
** Pure L3 communication with the help of kube-router/external bgp agent
** API aware L7 security policy
** Identity based application security policy
** Distributed load balancing using BPF hash table

== Known bugs

* Underlying SLE15 system breaks cluster with dynamic IPs, cluster nodes must have static IP (https://bugzilla.suse.com/show_bug.cgi?id=1121797)
** Solution:
+
The user must either assign static IP addresses for the nodes or do a hard coded mapping of addresses in the DHCP server
* No mirror configuration for Airgap for v4 (https://bugzilla.suse.com/show_bug.cgi?id=1125018)
* Velum fails to create new user (https://bugzilla.suse.com/show_bug.cgi?id=1121064).
** Solution: This can happen because of slow connection with registry.suse.com and so it takes more time than expected to pull down the images.
+
When this happens, a workaround is to try again, so the second time the image has already been pulled and so the time is shortened.
* OpenStack CPI not available in Velum (https://bugzilla.suse.com/show_bug.cgi?id=1126524)
* vmdk/vhdx images are broken because of partitions/device-mapper-multipath (https://bugzilla.suse.com/show_bug.cgi?id=1121433): This bug affects only cri-o on vmware. It does not affect docker.
* Local RMT/SMT mirror out of sync  (https://bugzilla.suse.com/show_bug.cgi?id=1127006)
* Update fails after master node reboot (https://bugzilla.suse.com/show_bug.cgi?id=1125444)
* Root filesystem is not read-only after first boot (https://bugzilla.suse.com/show_bug.cgi?id=1123820)
* Autoyast profile still enables admin's NTP server for nodes (https://bugzilla.suse.com/show_bug.cgi?id=1127362)
** Solution:
+
Download the autoyast profile from velum, and change the ntp configuration (see "NTP Client Configuration" above).
